{{- if and .Values.shelfarr.config.token (not .Values.shelfarr.secret.existingSecret) (ne .Values.shelfarr.secret.useSecret false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shelfarr-app.fullname" . }}-secret
  labels:
    {{- include "shelfarr-app.labels" . | nindent 4 }}
type: Opaque
data:
  ABS_TOKEN: {{ .Values.shelfarr.config.token | b64enc | quote }}
{{- end }}
