---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obsidian.fullname" . }}-env
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
data:
  PUID: "{{ .Values.obsidian.puid }}"
  PGID: "{{ .Values.obsidian.pgid }}"
  TZ: {{ .Values.obsidian.timezone | quote }}
  {{- if .Values.obsidian.customUser }}
  CUSTOM_USER: {{ .Values.obsidian.customUser | quote }}
  {{- end }}
  {{- if .Values.obsidian.password }}
  PASSWORD: {{ .Values.obsidian.password | quote }}
  {{- end }}
  {{- range $key, $val := .Values.extraEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
