{{- if and .Values.obsidian.password (not .Values.obsidian.existingSecret) (ne .Values.obsidian.useSecret false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obsidian.fullname" . }}-secret
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Values.obsidian.password | b64enc | quote }}
{{- end }}
