apiVersion: v1
kind: Service
metadata:
  name: {{ include "obsidian.fullname" . }}-service
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.service.httpEnabled }}
    - port: {{ .Values.service.httpPort | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if and .Values.service.restApi .Values.service.restApi.enabled }}
    - port: {{ .Values.service.restApi.port }}
      targetPort: rest-api
      protocol: TCP
      name: rest-api
    {{- end }}
  selector:
    {{- include "obsidian.selectorLabels" . | nindent 4 }}
