apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mousehole.fullname" . }}
  labels:
    {{- include "mousehole.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mousehole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mousehole.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mousehole.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "mousehole.fullname" . }}-env
          {{- if .Values.mousehole.existingSecret }}
          - secretRef:
              name: {{ .Values.mousehole.existingSecret }}
          {{- else if .Values.mousehole.authPassword }}
          - secretRef:
              name: {{ include "mousehole.fullname" . }}-secret
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if or .Values.env .Values.extraEnv }}
          env:
          {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          volumeMounts:
          {{- if or .Values.persistence.enabled .Values.persistence.existingClaim }}
            - name: data
              mountPath: {{ .Values.mousehole.stateDirPath }}
              readOnly: false
          {{- end }}
          {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
          {{- end }}
      
      volumes:
      {{- if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mousehole.fullname" . }}-data-pvc
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
