{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "copyparty.fullname" . }}-ingressroute
  labels:
    {{- include "copyparty.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "copyparty.fullname" . }}-service
          port: {{ .Values.service.port }}
  {{- if .Values.ingressRoute.tls.enabled }}
  tls:
    secretName: {{ .Values.ingressRoute.tls.secretName }}
  {{- end }}
{{- end }}