{{- if and .Values.mousehole.authPassword (not .Values.mousehole.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mousehole.fullname" . }}-secret
  labels:
    {{- include "mousehole.labels" . | nindent 4 }}
type: Opaque
data:
  MOUSEHOLE_AUTH_PASSWORD: {{ .Values.mousehole.authPassword | b64enc | quote }}
{{- end }}
