
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mousehole.fullname" . }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 250Mi
