apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzb.fullname" . }}
  labels:
    {{- include "sabnzb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sabnzb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sabnzb.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sabnzb.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "sabnzb.fullname" . }}-env
          {{- if .Values.secret.existingSecret }}
          - secretRef:
              name: {{ .Values.secret.existingSecret }}
          {{- else if and .Values.secret.enabled .Values.secret.data }}
          - secretRef:
              name: {{ include "sabnzb.fullname" . }}-secret
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if or .Values.env .Values.extraEnv }}
          env:
          {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if or (and .Values.persistence .Values.persistence.config .Values.persistence.config.enabled) (and .Values.persistence .Values.persistence.config .Values.persistence.config.existingClaim) }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if or (and .Values.persistence .Values.persistence.downloads .Values.persistence.downloads.enabled) (and .Values.persistence .Values.persistence.downloads .Values.persistence.downloads.existingClaim) }}
            - name: downloads
              mountPath: /downloads
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if and .Values.persistence .Values.persistence.config .Values.persistence.config.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
        {{- else if and .Values.persistence .Values.persistence.config .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "sabnzb.fullname" . }}-config-pvc
        {{- end }}
        {{- if and .Values.persistence .Values.persistence.downloads .Values.persistence.downloads.existingClaim }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.downloads.existingClaim }}
        {{- else if and .Values.persistence .Values.persistence.downloads .Values.persistence.downloads.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ include "sabnzb.fullname" . }}-downloads-pvc
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
