---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koreader-sync.fullname" . }}-env
  labels:
    {{- include "koreader-sync.labels" . | nindent 4 }}
data:
  RECEIVE_RANDOM_DEVICE_ID: "{{ .Values.koreaderSync.config.receiveRandomDeviceId }}"
  OPEN_REGISTRATIONS: "{{ .Values.koreaderSync.config.openRegistrations }}"