{{- if .Values.secretConfig.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copyparty.fullname" . }}-config-secret
  labels:
    {{- include "copyparty.labels" . | nindent 4 }}
type: Opaque
stringData:
  copyparty.conf: |
    {{ .Values.secretConfig.data | nindent 4 }}
{{- end }}
