apiVersion: v1
kind: Service
metadata:
  name: {{ include "copyparty.fullname" . }}-service
  labels:
    {{- include "copyparty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "copyparty.selectorLabels" . | nindent 4 }}
