apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smtp-aws-ses.fullname" . }}-config
  labels:
    {{- include "smtp-aws-ses.labels" . | nindent 4 }}
data:
  RELAY_HOST: {{ .Values.aws.relayHost | default (printf "[email-smtp.%s.amazonaws.com]" .Values.aws.region) | quote }}
  RELAY_PORT: "{{ .Values.aws.ses.port }}"
  FROM_EMAIL: "{{ .Values.aws.ses.fromEmail }}"
  TO_EMAIL: "{{ .Values.aws.ses.toEmail }}"
  RECIPIENT_RESTRICTIONS: "{{ .Values.postfix.recipientRestrictions | default "permit_mynetworks permit_sasl_authenticated reject_unauth_destination" }}"
  USE_TLS: "{{ .Values.aws.ses.useTls | default "yes" }}"
  TLS_VERIFY: "{{ .Values.aws.ses.tlsVerify | default "yes" }}"
  {{- if .Values.aws.ses.messageSizeLimit }}
  MESSAGE_SIZE_LIMIT: {{ .Values.aws.ses.messageSizeLimit | quote }}
  {{- end }}
  {{- if .Values.aws.ses.allowedSenderDomains }}
  ALLOWED_SENDER_DOMAINS: {{ .Values.aws.ses.allowedSenderDomains | quote }}
  {{- end }}
  {{- range $key, $val := .Values.extraConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}