{{- if or .Values.aws.secret.create (and (not .Values.aws.existingSecret) (or .Values.aws.relayLogin .Values.aws.relayPassword)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.secretName | default (printf "%s-secret" (include "smtp-aws-ses.fullname" .)) }}
  labels:
    {{- include "smtp-aws-ses.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.aws.relayLogin }}
  RELAY_LOGIN: {{ .Values.aws.relayLogin | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.relayPassword }}
  RELAY_PASSWORD: {{ .Values.aws.relayPassword | b64enc | quote }}
  {{- end }}
  {{- range $key, $val := .Values.aws.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
