{{- if and .Values.tunnel.token (not .Values.tunnel.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-env-secret
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
data:
  TUNNEL_TOKEN: {{ .Values.tunnel.token | b64enc | quote }}
{{- end }}
